name: Backend CI

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - dev
      - main

jobs:
  backend:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: backend

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: Give Gradle permission
        run: chmod +x ./gradlew

      - name: Run backend checks
        run: ./gradlew clean check jacocoTestReport

      - name: SonarCloud Scan
        if: github.ref == 'refs/heads/main' || github.base_ref == 'main'
        run: ./gradlew sonar
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}